# -*- coding: utf-8 -*-
"""Tercera Visualización.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FIWpNG30s78soKicr4kcDXvuXZU7WP9h
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install plotly

import plotly.graph_objects as go
import numpy as np
from scipy.interpolate import griddata
import plotly.graph_objects as go
import numpy as np
import pandas as pd

#Cargar el archivo .csv

file_path = '/content/drive/MyDrive/Student_Performance.csv'

df = pd.read_csv(file_path)



from scipy.interpolate import griddata
import plotly.graph_objects as go
import numpy as np


study_col = "Hours Studied"
sleep_col = "Sleep Hours"
perf_col  = "Performance Index"

# Definir bins
study_bins = np.arange(df[study_col].min(), df[study_col].max() + 1, 1)
sleep_bins = np.arange(df[sleep_col].min(), df[sleep_col].max() + 1, 1)

df_binned = df.copy()
df_binned["study_bin"] = pd.cut(df_binned[study_col], bins=study_bins, include_lowest=True)
df_binned["sleep_bin"] = pd.cut(df_binned[sleep_col], bins=sleep_bins, include_lowest=True)

# 3) Tabla 2D de medias de rendimiento
pivot = (
    df_binned
    .groupby(["study_bin", "sleep_bin"], observed=True)[perf_col]
    .mean()
    .unstack()
)

# Centros de los intervalos
x_centers = pivot.index.map(lambda iv: iv.mid).to_numpy()
y_centers = pivot.columns.map(lambda iv: iv.mid).to_numpy()

Z = pivot.to_numpy()


contour = go.Contour(
    x=x_centers, y=y_centers, z=Z.T,
    contours=dict(
        coloring="heatmap",
        showlabels=True, labelfont=dict(size=12)
    ),
    colorbar=dict(title="Nota media"),
    hovertemplate="Horas estudio=%{x:.1f}<br>Horas sueño=%{y:.1f}<br>Nota media=%{z:.1f}<extra></extra>"
)



fig = go.Figure(data=[contour])
fig.update_layout(
    title="RENDIMIENTO ACADEMICO SEGÚN HORAS DE ESTUDIO Y SUEÑO",
    xaxis_title="Horas de Estudio",
    yaxis_title="Horas de Sueño"
)
fig.show()

